spring:
    application:
        name: food-delivery-back-end
    datasource:
        url: jdbc:mysql://localhost:3306/food_delivery?createDatabaseIfNotExist=true
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update # create-drop, create, update, validate, none
        show-sql: false
        properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL8Dialect
    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

    data:
        redis:
            host: localhost
            port: 6379
            timeout: 3600000
api:
    prefix: /api/v1

jwtSecret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
jwtExpirationMs: 86400000